name: Filament
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Copy .env
        run: cp Laravel_app/.env.example Laravel_app/.env

      - name: Build containers
        run: docker compose build --no-cache

      - name: start docker compose 
        run: docker compose up -d

      - name: Install PHP dependencies
        run: docker compose exec -u root -w /var/www/html/Laravel_app php composer install --no-interaction --no-progress --prefer-dist

      - name: Fix ownership and permissions
        run: docker compose exec -u root php chown -R app:app /var/www/html
      
      - name: Generate application key
        run: docker compose exec -w /var/www/html/Laravel_app php php artisan key:generate

      - name: Install Node dependencies
        run: docker compose exec -w /var/www/html/Laravel_app php npm install

      - name: Compile front-end assets
        run: docker compose exec -w /var/www/html/Laravel_app php npm run build

      - name: ver posicion de trabajo
        run: |
          echo "Mostrando directorio actual:"
          pwd
          echo "Contenido del directorio:"
          ls -la

      - name: clear cache
        run: |
          docker compose exec -w /var/www/html/Laravel_app php php artisan config:clear
          docker compose exec -w /var/www/html/Laravel_app php php artisan route:clear
          docker compose exec -w /var/www/html/Laravel_app php php artisan view:clear

      - name: Run PHPUnit tests
        run: docker compose exec -T -w /var/www/html/Laravel_app php php artisan test

      - name: Shutdown Docker containers
        if: always()
        run: docker compose down -v

  # Job de despliegue a producción
  # deploy:
  #   # Se ejecuta en una máquina virtual Ubuntu
  #   runs-on: ubuntu-latest
    
  #   # Este job solo se ejecuta después de que el job 'test' se complete exitosamente
  #   needs: test
    
  #   # Condiciones para ejecutar el deploy:
  #   # 1. Solo cuando se hace push a la rama 'main'
  #   # 2. Solo si el job anterior (test) fue exitoso
  #   if: github.ref == 'refs/heads/main' && success()

  #   steps:
  #     # Paso 1: Descarga el código del repositorio en el runner de GitHub
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     # Paso 2: Conecta al servidor de producción via SSH y ejecuta comandos dentro de Docker
  #     - name: Deploy via SSH
  #       uses: appleboy/ssh-action@v1.1.0
  #       with:
  #         # Dirección IP o dominio del servidor (almacenado en GitHub Secrets)
  #         host: ${{ secrets.SSH_HOST }}
          
  #         # Usuario SSH del servidor (almacenado en GitHub Secrets)
  #         username: ${{ secrets.SSH_USER }}
          
  #         # Puerto SSH personalizado (almacenado en GitHub Secrets)
  #         port: ${{ secrets.SSH_PORT }}
          
  #         # Clave privada SSH para autenticación (almacenada en GitHub Secrets)
  #         key: ${{ secrets.SSH_KEY }}
          
  #         # Script que se ejecuta en el servidor remoto
  #         script: |
  #           cd /var/www/${{secrets.APP_NAME}}
  #           git pull origin main
  #           docker compose build --no-cache prod
        
  #           docker compose down
            
  #           docker compose up -d prod
            
  #           sleep 10
            
  #           docker compose exec -T php composer install --no-dev --optimize-autoloader --no-interaction
  #           docker compose exec -T php php artisan migrate --force
  #           docker compose exec -T php php artisan config:clear
  #           docker compose exec -T php php artisan cache:clear
  #           docker compose exec -T php php artisan route:clear
  #           docker compose exec -T php php artisan view:clear
  #           docker compose exec -T php php artisan filament:optimize-clear
  #           docker compose exec -T php php artisan optimize
  #           docker compose exec -T php php artisan filament:optimize
  #           docker compose exec -T php php artisan config:cache
  #           docker compose exec -T php php artisan route:cache
  #           docker compose exec -T php php artisan view:cache
            
  #           docker image prune -f